### ISSUE TITLE
Crashing with recent operator code

### ISSUE THREAD

**Issue by gibizer** [gibizer/operator-lint#9]
v0.4.0 crashing with operators bumped to golang 1.20

```
GOBIN=/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin go install github.com/gibizer/operator-lint@v0.4.0
go vet -vettool=/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin/operator-lint ./... ./api/...
# github.com/openstack-k8s-operators/nova-operator/api/v1beta1
api/v1beta1/novacell_types.go:199:2: C003: Field 'Schedule' has both a 'Optional' kubebuilder marker with a default value and an 'omitempty' tag. Either remove the default value or remove 'omitempty' or change the field to a pointer type
api/v1beta1/novacell_types.go:206:2: C003: Field 'ArchiveAge' has both a 'Optional' kubebuilder marker with a default value and an 'omitempty' tag. Either remove the default value or remove 'omitempty' or change the field to a pointer type
api/v1beta1/novacell_types.go:213:2: C003: Field 'PurgeAge' has both a 'Optional' kubebuilder marker with a default value and an 'omitempty' tag. Either remove the default value or remove 'omitempty' or change the field to a pointer type
# github.com/openstack-k8s-operators/nova-operator/test/functional_test
base.go:76: L001: on novacell_controller_test.go:625:55: unhandled type
panic: unhandled type *ast.IndexExpr

goroutine 9 [running]:
github.com/gibizer/operator-lint/pkg/base.(*BaseLinter).ExprName(0x0?, {0x82d258?, 0xc0002c8180?})
	/home/gibi/go/pkg/mod/github.com/gibizer/operator-lint@v0.4.0/pkg/base/helper.go:82 +0x459
github.com/gibizer/operator-lint/linters/envtest/T001.(*Linter).checkExpectCalls.func1({0x82b998?, 0xc0002d2680})
	/home/gibi/go/pkg/mod/github.com/gibizer/operator-lint@v0.4.0/linters/envtest/T001/T001.go:103 +0xa5
go/ast.inspector.Visit(0xc004ef6450, {0x82b998?, 0xc0002d2680?})
	/usr/lib/go-1.20/src/go/ast/walk.go:386 +0x31
go/ast.Walk({0x82b020?, 0xc004ef6450?}, {0x82b998?, 0xc0002d2680?})
	/usr/lib/go-1.20/src/go/ast/walk.go:51 +0x5f
go/ast.walkExprList({0x82b020, 0xc004ef6450}, {0xc000451ac0?, 0x1, 0x0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:26 +0x69
go/ast.Walk({0x82b020?, 0xc004ef6450?}, {0x82b858?, 0xc0002d26c0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:217 +0xd1a
go/ast.walkStmtList({0x82b020, 0xc004ef6450}, {0xc0002d2800?, 0x3, 0x71fc60?})
	/usr/lib/go-1.20/src/go/ast/walk.go:32 +0x69
go/ast.Walk({0x82b020?, 0xc004ef6450?}, {0x82b948?, 0xc0002c81b0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:234 +0xe0d
go/ast.Inspect(...)
	/usr/lib/go-1.20/src/go/ast/walk.go:397
github.com/gibizer/operator-lint/linters/envtest/T001.(*Linter).checkExpectCalls(0xc0001a2518?, 0x82d198?, {0x9fc7d8?, 0x1?}, {0xc0002c6740?, 0xa?})
	/home/gibi/go/pkg/mod/github.com/gibizer/operator-lint@v0.4.0/linters/envtest/T001/T001.go:100 +0xe5
github.com/gibizer/operator-lint/linters/envtest/T001.(*Linter).LintFile.func1({0x82b998?, 0xc0002d2880})
	/home/gibi/go/pkg/mod/github.com/gibizer/operator-lint@v0.4.0/linters/envtest/T001/T001.go:68 +0x13f
go/ast.inspector.Visit(0xc004ef3300, {0x82b998?, 0xc0002d2880?})
	/usr/lib/go-1.20/src/go/ast/walk.go:386 +0x31
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b998?, 0xc0002d2880?})
	/usr/lib/go-1.20/src/go/ast/walk.go:51 +0x5f
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bf38?, 0xc0002ce7b0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:111 +0x3bc
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b998?, 0xc0002d2900?})
	/usr/lib/go-1.20/src/go/ast/walk.go:143 +0x69c
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bb50?, 0xc000451c00?})
	/usr/lib/go-1.20/src/go/ast/walk.go:206 +0xbeb
go/ast.walkStmtList({0x82b020, 0xc004ef3300}, {0xc000469500?, 0xf, 0x80?})
	/usr/lib/go-1.20/src/go/ast/walk.go:32 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b948?, 0xc0002c82d0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:234 +0xe0d
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bc40?, 0xc0004628c0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:99 +0x298
go/ast.walkExprList({0x82b020, 0xc004ef3300}, {0xc0002d4260?, 0x2, 0xc004eec400?})
	/usr/lib/go-1.20/src/go/ast/walk.go:26 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b998?, 0xc0002d33c0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:144 +0x6bf
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bb50?, 0xc0004628e0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:206 +0xbeb
go/ast.walkStmtList({0x82b020, 0xc004ef3300}, {0xc000519b80?, 0x7, 0x6085b1?})
	/usr/lib/go-1.20/src/go/ast/walk.go:32 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b948?, 0xc0002c85a0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:234 +0xe0d
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bc40?, 0xc000463da0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:99 +0x298
go/ast.walkExprList({0x82b020, 0xc004ef3300}, {0xc000324760?, 0x2, 0x40?})
	/usr/lib/go-1.20/src/go/ast/walk.go:26 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b998?, 0xc0002e6f00?})
	/usr/lib/go-1.20/src/go/ast/walk.go:144 +0x6bf
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bb50?, 0xc000463dd0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:206 +0xbeb
go/ast.walkStmtList({0x82b020, 0xc004ef3300}, {0xc0007a2280?, 0x6, 0x6085b1?})
	/usr/lib/go-1.20/src/go/ast/walk.go:32 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b948?, 0xc0002c8d20?})
	/usr/lib/go-1.20/src/go/ast/walk.go:234 +0xe0d
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bc40?, 0xc00049e660?})
	/usr/lib/go-1.20/src/go/ast/walk.go:99 +0x298
go/ast.walkExprList({0x82b020, 0xc004ef3300}, {0xc000338280?, 0x2, 0x0?})
	/usr/lib/go-1.20/src/go/ast/walk.go:26 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82b998?, 0xc000331740?})
	/usr/lib/go-1.20/src/go/ast/walk.go:144 +0x6bf
go/ast.walkExprList({0x82b020, 0xc004ef3300}, {0xc00049e670?, 0x1, 0x6085b1?})
	/usr/lib/go-1.20/src/go/ast/walk.go:26 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82c0c8?, 0xc00021f590?})
	/usr/lib/go-1.20/src/go/ast/walk.go:318 +0x14fc
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bc90?, 0xc000331780?})
	/usr/lib/go-1.20/src/go/ast/walk.go:344 +0x191c
go/ast.walkDeclList({0x82b020, 0xc004ef3300}, {0xc000331ec0?, 0x3, 0x40e13e?})
	/usr/lib/go-1.20/src/go/ast/walk.go:38 +0x69
go/ast.Walk({0x82b020?, 0xc004ef3300?}, {0x82bbc8?, 0xc0002ae240?})
	/usr/lib/go-1.20/src/go/ast/walk.go:366 +0x17ac
go/ast.Inspect(...)
	/usr/lib/go-1.20/src/go/ast/walk.go:397
github.com/gibizer/operator-lint/linters/envtest/T001.(*Linter).LintFile(0xc0001a2518, 0xc0002ae240)
	/home/gibi/go/pkg/mod/github.com/gibizer/operator-lint@v0.4.0/linters/envtest/T001/T001.go:48 +0x198
github.com/gibizer/operator-lint/pkg/base.(*BaseLinter).baseRun(0xc0002171d0, 0x4ac9f7?)
	/home/gibi/go/pkg/mod/github.com/gibizer/operator-lint@v0.4.0/pkg/base/base.go:50 +0x9f
golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
	/home/gibi/go/pkg/mod/golang.org/x/tools@v0.10.0/go/analysis/unitchecker/unitchecker.go:354 +0x942
sync.(*Once).doSlow(0x72ff40?, 0xc00312bf50?)
	/usr/lib/go-1.20/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/lib/go-1.20/src/sync/once.go:65
golang.org/x/tools/go/analysis/unitchecker.run.func5(0xc0002ba000)
	/home/gibi/go/pkg/mod/golang.org/x/tools@v0.10.0/go/analysis/unitchecker/unitchecker.go:305 +0x1a5
golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0x0?)
	/home/gibi/go/pkg/mod/golang.org/x/tools@v0.10.0/go/analysis/unitchecker/unitchecker.go:376 +0x29
created by golang.org/x/tools/go/analysis/unitchecker.run.func6
	/home/gibi/go/pkg/mod/golang.org/x/tools@v0.10.0/go/analysis/unitchecker/unitchecker.go:375 +0x47
make: *** [Makefile:355: operator-lint] Error 1

````

**Comment by gibizer** [comment]
fixed by b85d75ab86d814647cbf992d2b6606111a58a335
